#!/usr/bin/env bash
#
# Frontend build:
#   1. Vendor vanilla ComfyUI v0.20.1 frontend (the contents of its `web/` dir)
#   2. Apply our patches (config.js loader + Cognito auth wrapper + queue button)
#   3. Copy our standalone /models page and viewer
#   4. Output to frontend/dist/ which CDK FrontendStack uploads to S3
#
# Run from repo root:  ./frontend/build.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST="$REPO_ROOT/frontend/dist"
COMFYUI_TAG="${COMFYUI_TAG:-v0.20.1}"
TMP_DIR="$(mktemp -d)"

trap 'rm -rf "$TMP_DIR"' EXIT

echo "==> Building frontend (ComfyUI tag: $COMFYUI_TAG)"
rm -rf "$DIST"
mkdir -p "$DIST"

# Step 1: Pull vanilla ComfyUI web dir
echo "==> Cloning ComfyUI $COMFYUI_TAG"
git clone --depth 1 --branch "$COMFYUI_TAG" \
  https://github.com/comfyanonymous/ComfyUI.git "$TMP_DIR/ComfyUI" 2>&1 | tail -3

if [ -d "$TMP_DIR/ComfyUI/web" ]; then
  cp -r "$TMP_DIR/ComfyUI/web/"* "$DIST/"
else
  echo "==> Note: ComfyUI's frontend has moved to a separate repo (Comfy-Org/ComfyUI_frontend)"
  echo "    Falling back to fetching from there..."
  git clone --depth 1 \
    https://github.com/Comfy-Org/ComfyUI_frontend.git "$TMP_DIR/frontend" 2>&1 | tail -3
  if [ -d "$TMP_DIR/frontend/dist" ]; then
    cp -r "$TMP_DIR/frontend/dist/"* "$DIST/"
  else
    echo "WARNING: ComfyUI frontend dist not found. You'll need to build it separately."
    echo "         See https://github.com/Comfy-Org/ComfyUI_frontend for build instructions."
    echo "         The auth + dispatcher patches won't be applied automatically."
  fi
fi

# Step 2: Apply our patches.
# We inject a small <script src="config.js"></script> + <script src="auth.js"></script>
# into index.html so the frontend uses our API + Cognito auth.
INDEX="$DIST/index.html"
if [ -f "$INDEX" ]; then
  echo "==> Patching index.html with config.js + auth.js"
  # Insert before </head>. Idempotent — only adds if not already there.
  if ! grep -q "config\.js" "$INDEX"; then
    if command -v gsed >/dev/null 2>&1; then SED=gsed; else SED=sed; fi
    "$SED" -i 's#</head>#<script src="config.js"></script><script src="auth.js"></script><script src="api-shim.js"></script></head>#' "$INDEX"
  fi
fi

# Step 3: Copy our patches and standalone pages.
cp "$REPO_ROOT/frontend/patches/auth.js"      "$DIST/auth.js"
cp "$REPO_ROOT/frontend/patches/api-shim.js"  "$DIST/api-shim.js"
cp "$REPO_ROOT/frontend/login/index.html"     "$DIST/login.html"
cp "$REPO_ROOT/frontend/models/index.html"    "$DIST/models.html"
cp "$REPO_ROOT/frontend/models/app.js"        "$DIST/models.js"
cp "$REPO_ROOT/frontend/viewer/index.html"    "$DIST/viewer.html"
cp "$REPO_ROOT/frontend/viewer/app.js"        "$DIST/viewer.js"
cp "$REPO_ROOT/frontend/styles.css"           "$DIST/comfy-aws-queue.css"

# Note: config.js is generated by the CDK FrontendStack at deploy time.
# It contains the API URL, Cognito pool ID, and client ID.

echo "==> Frontend built to $DIST"
echo "    Files:"
ls -lh "$DIST" | head -20
